[[plugins]]
  package = "netlify-plugin-flutter"

[plugins.inputs]
  channel = "stable"

[build]
  command = "curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.3-stable.tar.xz && tar xf flutter_linux_3.19.3-stable.tar.xz && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release"
  publish = "build/web"

# Add post-processing for environment variables
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.js]
  bundle = false
  minify = false
[build.processing.css]
  bundle = false
  minify = false

# Process environment variables in JS files
[[plugins]]
package = "@netlify/plugin-functions-core" 