// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVe70ciyaM-kI1ubD_XAgOOEMO7JwNn4',
    appId: '1:1055030588489:android:c83548390371fc88037b98',
    messagingSenderId: '1055030588489',
    projectId: 'cspportal',
    storageBucket: 'cspportal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEya_IwEqxkhVQu1U8GW0YLFWHwUyA5TQ',
    appId: '1:1055030588489:ios:af16e1e9dbe7fa45037b98',
    messagingSenderId: '1055030588489',
    projectId: 'cspportal',
    storageBucket: 'cspportal.firebasestorage.app',
    iosBundleId: 'com.example.smartLaser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEya_IwEqxkhVQu1U8GW0YLFWHwUyA5TQ',
    appId: '1:1055030588489:ios:af16e1e9dbe7fa45037b98',
    messagingSenderId: '1055030588489',
    projectId: 'cspportal',
    storageBucket: 'cspportal.firebasestorage.app',
    iosBundleId: 'com.example.smartLaser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvYQeP6Ik3eQNgXh69fjYJv8lGYr4Sdic',
    appId: '1:1055030588489:web:37640de41317aad7037b98',
    messagingSenderId: '1055030588489',
    projectId: 'cspportal',
    authDomain: 'cspportal.firebaseapp.com',
    storageBucket: 'cspportal.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYQeP6Ik3eQNgXh69fjYJv8lGYr4Sdic',
    appId: '1:1055030588489:web:37640de41317aad7037b98',
    messagingSenderId: '1055030588489',
    projectId: 'cspportal',
    authDomain: 'cspportal.firebaseapp.com',
    storageBucket: 'cspportal.firebasestorage.app',
  );

}